# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    disable_automatic_code_signing(path: "Runner.xcodeproj")
    match(type: "appstore", readonly: true, git_url: "git@github.com:codekrafter/match.git")
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_testflight
    #enable_automatic_code_signing(path: "Runner.xcodeproj")
  end

  desc "Push a new beta build to Firebase Distribution"
  lane :firebase do
    disable_automatic_code_signing(path: "Runner.xcodeproj")
    #match(type: "appstore", readonly: false, git_url: "git@github.com:codekrafter/match.git", clone_branch_directly: true)
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    firebase_app_distribution(
      app: "1:161534165723:ios:1759531d0b1c5a8c7dc2fe"
    )
    #enable_automatic_code_signing(path: "Runner.xcodeproj")
  end
end
