# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Submit a new Beta Build to Firebase Distribution"
    lane :firebase do
        #build_android_app(...) # build_android_app is a built-in fastlane action.

        firebase_app_distribution(
            app: "1:161534165723:android:6c9bab3a728ff27a7dc2fe",
            #testers: "tester1@company.com, tester2@company.com",
            release_notes: "Test release notes",
            #firebase_cli_path: "C:\Users\codek\AppData\Roaming\npm\firebase"
            apk_path: "../build/app/outputs/apk/release/app-release.apk"
        )

      end
end
